"""
Bake a trained world into data a web page can run.

    python3 train/export_demo.py --name dig10 --best

Writes staging/ncpu-data.js: the kernel bank, the interaction matrix, the three
globals, the learned chemical seed pattern and a handful of MNIST digits. The
page then runs the same arithmetic the trainer did -- so what you see in the
browser is the trained simulation, not a recording of it.

Two facts make it cheap enough for plain JavaScript.

**The static channels are convolved once.** Channels 0..n_static-1 hold the
digit and never move, so their contribution to the affinity is fixed for a given
digit and is computed when the digit is drawn, not every step.

**The crowding blur is one convolution, not C.** fieldlife computes N per
channel against a gaussian that differs between RGBA layers only where every
kernel in the layer is exactly zero AND the weight is already below 1e-4 -- the
window corners. This checks they agree and exports one, so the page can blur the
summed density instead of every channel separately.
"""

import argparse, json, os, sys
import numpy as np, torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import digits as dg, fieldlife as fl

HERE = os.path.dirname(os.path.abspath(__file__))
STAGING = os.path.join(HERE, "..", "staging")


def r5(a):
    return [round(float(v), 6) for v in np.asarray(a).ravel()]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", default="dig10")
    ap.add_argument("--best", action="store_true")
    ap.add_argument("--static", type=int, default=4)
    ap.add_argument("--samples", type=int, default=24)
    ap.add_argument("--out", default=os.path.join(STAGING, "ncpu-data.js"))
    a = ap.parse_args()

    run = os.path.join(HERE, "runs", a.name)
    cfg = json.load(open(os.path.join(
        run, "preset-best.json" if a.best else "preset.json")))
    C, N = cfg["C"], cfg["N"]
    t = cfg.get("_task", {})
    grid = N
    ring = t.get("ring", dg.RING)
    digit_px = t.get("digit", dg.DIGIT)
    nchem = C - a.static - 1

    KR = max(3, min(fl.KMAX, round(max(k["R"] for k in cfg["kernels"][:C]))))
    kern = fl.bake_from_config(cfg["kernels"], C, KR, dtype=torch.float64).numpy()

    # the crowding blur, and the check that one is enough
    g = fl.crowd_gaussian(KR, torch.tensor(kern), C, dtype=torch.float64).numpy()
    spread = float(np.abs(g - g[0]).max())
    assert spread < 1e-9, f"per-channel crowding blurs differ by {spread:g}"

    # the learned chemical seed, at unit mass per channel so the page can scale
    # it by whatever the drawn digit weighs
    siren = None
    ck = os.path.join(run, "ckpt.pt")
    if os.path.exists(ck):
        st = torch.load(ck, weights_only=False)
        if st.get("siren"):
            siren = dg.SirenSeed(grid, nchem, 32, 2)
            siren.load_state_dict(st["siren"])
    if siren is not None:
        with torch.no_grad():
            chem = siren(1.0).numpy()
    else:
        rng = np.random.default_rng(0)
        chem = np.stack([dg.Geometry(grid=grid).ball(rng, 1.0, jitter=0.0)
                         for _ in range(nchem)])
    # crop to what is actually non-zero, so the page carries a patch not a field
    nz = np.argwhere(chem.sum(0) > 1e-12)
    y0, x0 = nz.min(0); y1, x1 = nz.max(0) + 1
    patch = chem[:, y0:y1, x0:x1]

    geo = dg.Geometry(grid=grid, digit=digit_px, ring=ring)
    ball = geo.ball(np.random.default_rng(0), 1.0, jitter=0.0)
    bz = np.argwhere(ball > 1e-12)
    by0, bx0 = bz.min(0); by1, bx1 = bz.max(0) + 1

    x, y = dg.load("test")
    samples = [r5(geo.place(x[i]) [:, :]) for i in range(a.samples)]
    # store the digit at its own resolution, centred by the page
    o = (grid - digit_px) // 2
    small = [r5(np.asarray(geo.place(x[i]))[o:o + digit_px, o:o + digit_px])
             for i in range(a.samples)]

    data = {
        "name": a.name, "C": C, "grid": grid, "KR": KR, "K": 2 * KR + 1,
        "nStatic": a.static, "ptr": a.static, "nChem": nchem,
        "digitPx": digit_px, "ring": ring, "regionR": dg.REGION_R,
        "nClass": dg.NCLASS, "chem": dg.CHEM, "pointer": 1.0,
        "force": cfg["force"], "repel": cfg["repel"], "beta": cfg["beta"],
        "mat": r5(cfg["mat"]),
        "kern": r5(kern), "blur": r5(g[0]),
        "chemPatch": {"y": int(y0), "x": int(x0),
                      "h": int(y1 - y0), "w": int(x1 - x0),
                      "v": r5(patch)},
        "ballPatch": {"y": int(by0), "x": int(bx0),
                      "h": int(by1 - by0), "w": int(bx1 - bx0),
                      "v": r5(ball[by0:by1, bx0:bx1])},
        "digits": small, "labels": [int(v) for v in y[:a.samples]],
        "acc": cfg.get("_acc"), "bestAt": cfg.get("_bestAt"),
    }
    os.makedirs(STAGING, exist_ok=True)
    with open(a.out, "w") as fh:
        fh.write("// generated by train/export_demo.py -- do not edit\n")
        fh.write("window.NCPU = ")
        json.dump(data, fh, separators=(",", ":"))
        fh.write(";\n")
    kb = os.path.getsize(a.out) / 1024
    print(f"{a.name}: C={C} grid={grid} stencil={2*KR+1} nchem={nchem}")
    print(f"  crowding blurs agree to {spread:.1e}, exported once")
    print(f"  chemical seed patch {patch.shape}, ball patch "
          f"{(by1-by0, bx1-bx0)}, {a.samples} sample digits")
    print(f"  wrote {a.out}  ({kb:.0f} KB)")


if __name__ == "__main__":
    main()
