"""
Every run, scored the same way, written to docs/results.md.

    python3 train/report.py

Generated from the run directories rather than kept by hand, so it cannot
drift from what actually happened. The score is the horizon curve weighted
toward the far end -- reaching the shape is easy and holding it is not, so a
world that decays is not a better world for having been briefly sharper.
"""

import csv
import glob
import json
import os
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
HORIZONS = [16, 32, 64, 128, 256, 512]
WEIGHTS = [0.25, 0.5, 1, 2, 3, 4]


def score(hz):
    """None unless the run measured every horizon.

    Runs from before h256 and h512 existed carry four values, and zipping four
    against six weights silently drops the far end while still dividing by the
    full weight sum -- which made an early checkpoint look four times better
    than the world that actually ships. Refuse to score those instead.
    """
    if not hz or len(hz) != len(WEIGHTS):
        return None
    return sum(h * w for h, w in zip(hz, WEIGHTS)) / sum(WEIGHTS)


def read(run):
    d = os.path.join(HERE, "runs", run)
    log = os.path.join(d, "log.csv")
    if not os.path.exists(log):
        return None
    rows = [r for r in csv.DictReader(open(log)) if r.get("iter", "").isdigit()]
    if not rows:
        return None
    cfg, best = {}, None
    for name in ("preset-best.json", "preset.json"):
        p = os.path.join(d, name)
        if os.path.exists(p):
            try:
                cfg = json.load(open(p))
                if "_horizons" in cfg:
                    best = cfg
                break
            except json.JSONDecodeError:
                pass
    scale = {}
    sp = os.path.join(d, "scale.json")
    if os.path.exists(sp):
        try:
            scale = json.load(open(sp))
        except json.JSONDecodeError:
            pass
    hz = best["_horizons"] if best else None
    if hz is not None and len(hz) != len(WEIGHTS):
        hz = None
    ks = cfg.get("kernels") or [{}]
    return {
        "run": run,
        "iters": int(rows[-1]["iter"]),
        "C": cfg.get("C", 0),
        "grid": scale.get("grid", cfg.get("N", 0)),
        "span": scale.get("span", 0),
        "lobes": len(ks[0].get("terms", [])),
        "orders": ",".join(str(m) for m in sorted(
            {t.get("m", 0) for k in ks for t in k.get("terms", [])})) or "-",
        "reach": round(max((k.get("R", 0) for k in ks), default=0), 1),
        "rung": 1 if "_note" in cfg else 0,
        "hz": hz,
        "score": score(hz) if hz else None,
        "hours": float(rows[-1]["secs"]) / 3600,
    }


def main():
    runs = [r for r in (read(os.path.basename(d))
                        for d in sorted(glob.glob(os.path.join(HERE, "runs", "*"))))
            if r]
    scored = sorted([r for r in runs if r["score"]], key=lambda r: r["score"])
    rest = [r for r in runs if not r["score"]]

    out = ["# Results", "",
           "Every run, scored the same way. Generated by `train/report.py` from the",
           "run logs, so it cannot drift from what happened.", "",
           "The score weights the horizon curve toward the far end: reaching the shape",
           "is easy and holding it is not, so a world that decays is not a better world",
           "for having been briefly sharper. Lower is better throughout.", "",
           f"_Last generated {datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC._", "",
           "| run | score | grid | animal | reach | C | lobes | orders | iters | hours |",
           "|---|---|---|---|---|---|---|---|---|---|"]
    for r in scored:
        out.append(f"| `{r['run']}`{' (rung 1)' if r['rung'] else ''} | **{r['score']:.5f}** | "
                   f"{r['grid']} | {r['span'] or '-'} | {r['reach']} | {r['C']} | "
                   f"{r['lobes']} | {r['orders']} | {r['iters']} | {r['hours']:.1f} |")
    if rest:
        out += ["", "Runs from before the long horizons were measured, so not comparable:",
                "", "| run | iters | C | grid |", "|---|---|---|---|"]
        for r in rest:
            out.append(f"| `{r['run']}` | {r['iters']} | {r['C']} | {r['grid']} |")

    out += ["", "## Horizon curves", "",
            "Distance from the target, from a fresh seed, after N steps.", "",
            "| run | " + " | ".join(f"h{h}" for h in HORIZONS) + " |",
            "|---|" + "---|" * len(HORIZONS)]
    for r in scored:
        out.append(f"| `{r['run']}` | " + " | ".join(f"{v:.4f}" for v in r["hz"]) + " |")
    out.append("")

    p = os.path.join(ROOT, "docs", "results.md")
    open(p, "w").write("\n".join(out))
    print(f"wrote {p}  ({len(scored)} scored runs, {len(rest)} older)")
    for r in scored[:4]:
        print(f"  {r['score']:.5f}  {r['run']}")


if __name__ == "__main__":
    main()
